-- Iceborne Hunter Notes v22
-- 思い出画像機能の初回セットアップ
-- Supabase > SQL Editor でこのSQLを1回実行してください。

create table if not exists public.hunter_images (
  id bigint generated by default as identity primary key,
  hunter_record_id bigint not null references public.hunters(id) on delete cascade,
  storage_path text not null unique,
  uploaded_by text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists hunter_images_hunter_record_id_created_at_idx
  on public.hunter_images (hunter_record_id, created_at desc);

alter table public.hunter_images enable row level security;

grant select, insert on public.hunter_images to anon, authenticated;
grant usage, select on sequence public.hunter_images_id_seq to anon, authenticated;

drop policy if exists "hunter images public read" on public.hunter_images;
create policy "hunter images public read"
  on public.hunter_images
  for select
  to anon, authenticated
  using (true);

drop policy if exists "hunter images public insert" on public.hunter_images;
create policy "hunter images public insert"
  on public.hunter_images
  for insert
  to anon, authenticated
  with check (
    hunter_record_id is not null
    and char_length(btrim(uploaded_by)) between 1 and 40
    and char_length(coalesce(caption,'')) <= 200
  );

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'hunter-images',
  'hunter-images',
  true,
  31457280,
  array['image/jpeg','image/jpg','image/png','image/webp','image/heic','image/heif','image/gif']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "hunter images storage upload" on storage.objects;
create policy "hunter images storage upload"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'hunter-images');

-- 画像はpublic bucketで配信するため、公開URLを知っている人は閲覧できます。
-- アプリ自体が共有DB前提なので、その運用に合わせた設定です。


-- v23: 元画像アップロード対応のため、バケット上限を30MBへ拡張。
